/* Auto-generated by gen_theme.sh — do not edit */
#ifndef THEME_H
#define THEME_H
#include <stddef.h>

#define UI_TITLE "JAM"
#define UI_SIZE_INFO "23 KB / 18 KB brain"

static const char *UI_SUBS[] = {"Atari. Czech. Math. Integers.", "18 KB brain. Thinks in chains.", "Try: 2+3, COUNT 5, POKEY, LOVE", NULL};

static const char *UI_SUGS[] = {"TRY 2+3", "TRY COUNT 5", "TRY BIN 7", "TRY REV DOG", "TRY ZORK", "TRY STAR RAIDER", "TRY ATARI", "TRY ANTIC", NULL};

static const char *UI_DREAMS[] = {"3+4", "COUNT 5", "BIN 7", "REV DOG", "LOVE", "42", "WHO ARE YOU", "DO YOU THINK", "HELLO", "BEER", "NEXT 2 4 6", "STAR RAIDERS", "RUDE", "HOPE", "POKEY", "SPAM", NULL};

#endif /* THEME_H */
