#!/bin/sh
# gen_theme.sh <td_file> <out_header>
# Parse @title/@sub/@sug/@dream metadata from training data and emit a C header.

set -e

TD="$1"
OUT="$2"

if [ -z "$TD" ] || [ -z "$OUT" ]; then
    printf 'Usage: gen_theme.sh <td_file> <out_header>\n' >&2
    exit 1
fi

awk '
BEGIN {
    title = "JAM"
    nsub = 0; nsug = 0; ndream = 0
    sz = ""; br = ""
}
/^@title /  { title = substr($0, 8) }
/^@size /   { sz    = substr($0, 7) }
/^@brain /  { br    = substr($0, 8) }
/^@sub /    { subs[nsub++]   = substr($0, 6) }
/^@sug /    {
    s = substr($0, 6)
    if (length(s) > 15) s = substr(s, 1, 15)
    sugs[nsug++] = s
}
/^@dream /  {
    d = substr($0, 8)
    if (length(d) > 15) d = substr(d, 1, 15)
    dreams[ndream++] = d
}
END {
    if (nsug == 0) { sugs[0] = "HELP"; nsug = 1 }
    base = nsug
    while (nsug < 8) { sugs[nsug] = sugs[nsug % base]; nsug++ }

    if (ndream == 0) {
        for (i = 0; i < 8; i++) dreams[i] = sugs[i]
        ndream = 8
    }
    base = ndream
    while (ndream < 16) { dreams[ndream] = dreams[ndream % base]; ndream++ }

    print "/* Auto-generated by gen_theme.sh — do not edit */"
    print "#ifndef THEME_H"
    print "#define THEME_H"
    print "#include <stddef.h>"
    print ""
    printf "#define UI_TITLE \"%s\"\n", title
    if (sz != "" && br != "")
        printf "#define UI_SIZE_INFO \"%s KB / %s KB brain\"\n", sz, br
    else if (sz != "")
        printf "#define UI_SIZE_INFO \"%s KB\"\n", sz
    print ""
    printf "static const char *UI_SUBS[] = {"
    for (i = 0; i < nsub; i++) {
        if (i > 0) printf ", "
        printf "\"%s\"", subs[i]
    }
    if (nsub == 0) printf "NULL"
    else printf ", NULL"
    print "};"
    print ""
    printf "static const char *UI_SUGS[] = {"
    for (i = 0; i < 8; i++) {
        if (i > 0) printf ", "
        printf "\"%s\"", sugs[i]
    }
    print ", NULL};"
    print ""
    printf "static const char *UI_DREAMS[] = {"
    for (i = 0; i < 16; i++) {
        if (i > 0) printf ", "
        printf "\"%s\"", dreams[i]
    }
    print ", NULL};"
    print ""
    print "#endif /* THEME_H */"
}
' "$TD" > "$OUT"

printf '  theme: %s (title="%s")\n' "$OUT" "$(awk '/^@title /{print substr($0,8)}' "$TD")"
