/* Auto-generated by gen_theme.sh — do not edit */
#ifndef THEME_H
#define THEME_H
#include <stddef.h>

#define UI_TITLE "JAM KID"
#define UI_SIZE_INFO "80 KB / 76 KB brain"

static const char *UI_SUBS[] = {"LITTLE JAM IN ATARI", "SMALL BRAIN BIG WHY", "PRETEND PLAY IN RAM", "Try: NAME, ORCA, SHARK, STORY", "More: DOLPHIN, WHALE, PADDY, COLORS, HUG", NULL};

static const char *UI_SUGS[] = {"NAME", "HELLO", "ORCA", "SHARK", "DOLPHIN", "STORY", "PADDY", "HUG", NULL};

static const char *UI_DREAMS[] = {"HELLO", "WHY", "STORY", "POKEY", "MOON", "MONSTER", "TOWEL", "COUNT 5", "RAIN", "CAT", "SPACE", "BEEP", "AGAIN", "WHO AM I", "DREAM", "SUN", NULL};

#endif /* THEME_H */
