/* Auto-generated by gen_theme.sh — do not edit */
#ifndef THEME_H
#define THEME_H
#include <stddef.h>

#define UI_TITLE "PICO JAM"
#define UI_SIZE_INFO "4 KB / 1.5 KB brain"

static const char *UI_SUBS[] = {"just atari model", "1.5 kb. roasts llms. does math.", NULL};

static const char *UI_SUGS[] = {"TRY 3+4", "TRY GPT", "TRY CNT5", "TRY BIN7", "TRY 9+9", "TRY WHO", "TRY 42", "TRY HELP", NULL};

static const char *UI_DREAMS[] = {"TRY 3+4", "TRY GPT", "TRY CNT5", "TRY BIN7", "TRY 9+9", "TRY WHO", "TRY 42", "TRY HELP", "TRY 3+4", "TRY GPT", "TRY CNT5", "TRY BIN7", "TRY 9+9", "TRY WHO", "TRY 42", "TRY HELP", NULL};

#endif /* THEME_H */
