/* Auto-generated by gen_theme.sh — do not edit */
#ifndef THEME_H
#define THEME_H

#define UI_TITLE "JAM XE"
#define UI_SIZE_INFO "80 KB / 76 KB brain"

static const char *UI_SUBS[] = {"JAM XE 130XE REAL IRON", "512 HIDDEN FROZEN ANCHOR", "D J ATTENTION NO CLOUD", "Try: 3+4, BIN 7, COUNT 5, REV DOG", "More: POKEY, TRON, ZORK, 42, ATARI", NULL};

static const char *UI_SUGS[] = {"3+4", "BIN 7", "COUNT 5", "REV DOG", "POKEY", "TRON", "ATARI", "42", NULL};

static const char *UI_DREAMS[] = {"HELLO JAM", "3+4", "COUNT 5", "BIN 7", "REV DOG", "ROAST GROK", "CLAUD CLAUN", "POKEY", "TRON", "BTTF", "MULE", "DEPECHE MODE", "STAR RAIDERS", "ATARI", "ANTIC", "WALKMAN", NULL};

#endif /* THEME_H */
