/* Auto-generated by gen_theme.sh — do not edit */
#ifndef THEME_H
#define THEME_H
#include <stddef.h>

#define UI_TITLE "TRANSFORMER"

static const char *UI_SUBS[] = {"Decoder-only character model", "Pi Zero W", NULL};

static const char *UI_SUGS[] = {"HOW ARE YOU", "WHAT IS LOVE", "TELL A STORY", "WHAT IS ATARI", "COUNT 5", "WHO ARE YOU", "HOW ARE YOU", "WHAT IS LOVE", NULL};

static const char *UI_DREAMS[] = {"HOW ARE YOU", "WHAT IS LOVE", "TELL A STORY", "WHAT IS ATARI", "COUNT 5", "WHO ARE YOU", "WHY AM I HERE", "WHAT IS TIME", "HOW ARE YOU", "WHAT IS LOVE", "TELL A STORY", "WHAT IS ATARI", "COUNT 5", "WHO ARE YOU", "WHY AM I HERE", "WHAT IS TIME", NULL};

#endif /* THEME_H */
